### ISSUE TITLE
Spinoff "Pi" calculation to hpc-parallel novice

### ISSUE THREAD

**Issue by wirawan0** [hpc-carpentry/coordination#103]
This is per 2022-02-17 discussion on

https://codimd.carpentries.org/eT62gOnGTquEfaqLozRB0g?view

There was this mention:

>  There is a negative review at http://pracrand.sourceforge.net/PractRand.txt of https://csrc.nist.gov/Projects/Random-Bit-Generation/Documentation-and-Software - Would be good to discuss inclusion of this kind of material in the lessons.

I would like to know what the "negative review" mentioned in these two links. I read them, couldn't make out what this negative review is. Except probably the unreliability of doing "just any" random number generators for highly scalable parallel computation. Which is really true and will bite people who scale up to many many number of threads or processes w/ independent random streams.

**Comment by bkmgit** [comment]
The most used statistical tests currently are [http://pracrand.sourceforge.net/](http://pracrand.sourceforge.net) and [TestU01](https://github.com/umontreal-simul/TestU01-2009).  The NIST tests seem not to be as demanding.
