### ISSUE TITLE
Candidate venue for cloud HPC?

### ISSUE THREAD

**Issue by reid-a** [hpc-carpentry/coordination#109]
I recently learned (from @tkphd) about the [Mass Open Cloud](https://massopen.cloud/) project. They seem to have a community mission to make resources available to "researchers and industry". Could this be a candidate venue for transient instructional HPC clusters?

**Comment by tkphd** [comment]
> The MOC is being depreciated and moving to the [NERC](https://nerc.mghpcc.org/). If you’re looking to create a new project or account, please do so on the NERC.

**Comment by tkphd** [comment]
@ocaisa has us covered through the end of 2023.
