### ISSUE TITLE
2022 Elections

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/coordination#114]
Dear @hpc-carpentry/hpc-intro-maintainers,

On behalf of the HPC Carpentry Steering Committee, you are cordially invited to participate in our annual Election!
The [process](https://github.com/hpc-carpentry/coordination/issues/36) is the same as last year, _viz._ 

- If you wish to nominate yourself or someone else for a seat on the Committee, please leave their name and GitHub handle in a comment on this Issue.
- If you wish to vote for someone, leave a `:+1:` (:+1:) reaction on their nomination comment.
- Any valid nominee (not bot accounts) receiving _5 or more votes_ before the vote is called at the June Coordination Meeting will be considered duly elected.

Sincerely,  
  Andrew Reid, @reid-a  
  Alan O'Cais, @ocaisa  
  Annajiat Alim Rasel, @annajiat  
  Trevor Keller, @tkphd  
  Wirawan Purwanto, @wirawan0

---

The Steering Committee must have at least three members; no upper limit has been set. Each member will be elected for a term of one (1) year. The members are expected to foster the HPC Carpentry organization and its lessons, guide curriculum development following The Carpentries Handbook, and participate in discussions with The Carpentries in a representative capacity to help us navigate the pathway to induction as an official Lesson Program. An important additional task of this inaugural Steering Committee will be to formalize a set of by-laws outlining our governance structure. The time commitment of service on the Steering Committee is unknown, but is not negligible.

Participation in some of the recent Coordination Meetings and Coworking Hours to date is desirable, but not a strict prerequisite: these elections are democratic, and any member of our community is eligible to join the Steering Committee. In case of scheduling conflicts with the existing meeting times, the monthly Coordination meeting time will be changed so that issues of governance may be discussed with full participation of all members of the Committee.

## Nominations

* ***Ask before nominating someone else.*** In the event a nominee wishes to decline a nomination, they should do this in a comment on the election issue. The comment nominating them will then be struck through (not deleted, in case of repeat nominations).
* To nominate a community member, please leave a comment with *a single name and GitHub handle*.
* Vote on as many nominees as you wish by "reacting" to their name with `:+1:` (:+1:, in favor).
* A nominee receiving at least a majority of the quorum of votes in favor, and less than a minority of votes opposed, shall be elected to a seat.
* As an asynchronous process, nominations and voting can (and should) be conducted simultaneously.
* The Election Issue shall remain open until the next Coordination Meeting, currently scheduled for 16 June 2022.

## Basic Bylaws

* The Steering Committee shall have at least three active members.
* Seats on the Steering Committee shall come up for election annually.
* In the event that a seat is vacated, voluntarily or following removal, a by-election may be held.

**Comment by tkphd** [comment]
Andrew Reid, @reid-a

**Comment by tkphd** [comment]
Trevor Keller, @tkphd

**Comment by HaoZeke** [comment]
As in the previous year, I'd like to nominate myself. I haven't had much time to take part so far but believe I would be well placed to bring in a more Nordic perspective (from cross-connections to the NordicRSE, Carpentries, Icelandic HPC association and other relevant communities)

@HaoZeke .

**Comment by wirawan0** [comment]
@wirawan0

I hope more people will step up!

**Comment by annajiat** [comment]
Annajiat Alim Rasel, @annajiat

**Comment by tkphd** [comment]
This year's election is now closed. Thank you to everyone who voted! Our entire Steering Committee was re-elected, and we welcome a sixth member. Congratulations to

- Alan (@ocaisa)
- Andrew (@reid-a)
- Annajiat (@annajiat)
- Rohit (@HaoZeke)
- Trevor (@tkphd)
- Wirawan (@wirawan0)

Thanks again for participating in this democratic process, which will return next May--June. Until then, see you at our two monthly meetings!
