### ISSUE TITLE
Roadmap for HPC Carpentry's Path to the Carpentries

### ISSUE THREAD

**Issue by reid-a** [hpc-carpentry/coordination#119]
This issue is a venue for discussion about drafting a roadmap for HPC Carpentry's entry into the Carpentries, to frame the (near-term!) discussion with the Carpentries executive team, and by way of follow-up to our very successful [breakout session](https://codimd.carpentries.org/Epr50mepQ-WWNsLA1M1UlA) at CarpentryCon.

The basic idea is to outline what we have accomplished already, and what we still need to work on, in order to ensure that we both add value to the Carpentries community at large, and get value out of it.

Some initial thoughts derived from the break-out session:

- We should have some solid lesson content organized into coherent workshops (we do!)
- We should have the technical means to stand up clusters for instruction in the cloud (we do!)
- There should be resources to fund this (there could be, conversation to be had)
- Our lessons are somewhat specialized, with snippets etc., we should provide resources to on-board new instructors on our material
  - Aligned with a Carpentries initiative along similar lines across other lessons
  - Complements but does not replace the pedagogical/empathic/inclusive parts of existing instructor training
  - Helps build the learner-to-instructor pipeline
- We should have a robust contributor community that's ready to scale (do we?)

This is all preliminary, additional feedback and new ideas or changes in emphasis are most welcome!

**Comment by tkphd** [comment]
This is the topic of discussion for the [3 Nov 2022 Coworking Hours](https://codimd.carpentries.org/ZsPdpbvWTl-jL-Uvdqzi1g?view), along with COWS Analysis:
<a title="Trevor Keller, CC BY-SA 4.0 &lt;https://creativecommons.org/licenses/by-sa/4.0&gt;, via Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:COWS_Analysis_matrix.svg"><img width="400" alt="COWS Analysis matrix" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/COWS_Analysis_matrix.svg/600px-COWS_Analysis_matrix.svg.png"></a>

**Comment by tkphd** [comment]
Application to the Lesson Program Incubator has been sent.
