### ISSUE TITLE
Task Force on Bringing hpc-intro into the carpentries

### ISSUE THREAD

**Issue by psteinb** [hpc-carpentry/coordination#12]
As announced during carpentrycon@home 2020, we would like to bring a task force into life that coordinates/drives the efforts to bring the hpc-carpentry/hpc-intro material into the carpentries.

Some thoughts around this:
- after collecting volunteers' names, we start to work after the summer break of 2020 (most likely early September 2020)
- we put up a light weight organisation around this task force:
  - biweekly calls to coordinate and address ongoing issues
  - weekly coworking hours
  - github management roles to distribute the work on reviewing incoming contributions 

Thoughts and feedback is highly welcome.

**Comment by tkphd** [comment]
During CarpentryCon@Home, the following enthusiastic heroes indicated interest in joining our task force:

* @tkphd 
* @megan-guidry
* @reid-a
* @mikerenfro
* @annajiat
* @colinsauze
* @pete-lawson

https://github.com/hpc-carpentry/hpc-intro/pull/166 adds them as code owners on hpc-intro, so they would get review requests for each new pull request. Further contact info is available on the Etherpad: https://pad.carpentries.org/cchome-hpc-carpentry

**Comment by psteinb** [comment]
Thanks @tkphd for bringing the volunteers in. That is awesome.

**Comment by tkphd** [comment]
No time like the present to ~rope people in~ welcome our new friends :-)

**Comment by colinsauze** [comment]
Or to find new forms of procrastination

**Comment by willfurnass** [comment]
@tkphd I'd also be interested in being on this list.

**Comment by HaoZeke** [comment]
I'd be happy to help with this!

**Comment by verolero86** [comment]
I'd be interested as well!

**Comment by psteinb** [comment]
For those that can invest about 1h of video watching to get up to speed, here is the recording from our CarpentryCon@Home session:
https://www.youtube.com/watch?v=Xo3Ab2GFj24&feature=youtu.be
Enjoy!

**Comment by tkphd** [comment]
@psteinb also has a Request for Diversity out: <https://twitter.com/psteinb_/status/1288381784992997377>. Please consider a RT to amplify its reach, or contact individuals who might be interested in helping and somehow have not yet heard about us. 

Gentle reminder not to dump our DE&I problems onto minority members as the price of entry. We want to grow our diverse team and ensure we are welcoming a rainbow of perspectives, not saddling those with diverse perspectives with the burdens of token membership. Do good.

**Comment by riveraresearch** [comment]
happy to help!

**Comment by Rabab53** [comment]
happy to join!

**Comment by jlevites** [comment]
happy to help!

**Comment by psteinb** [comment]
Dear all, 
we are offering an online tour around the hpc-carpentry material - so that new maintainers get a effective introduction to the material. 

As we have interested parties from time zones in Europe, the US and New Zealand/Australia, we have identified a very narrow time window next week where both @tkphd and myself can participate.
I have created a when2meet page for you to provide your availability:
https://www.when2meet.com/?9450912-J7TTv

Please participate in the poll by this week-end, so that we can announce the connection details on Monday. If need be, we can reiterate with such a guided tour in September.
Best,
@psteinb

**Comment by jevbelikov** [comment]
I'd be interested, too.

**Comment by psteinb** [comment]
Dear all,

we have converged on a time and date that hopefully will serve everybody.
Aug 6, 9pm UTC
https://www.timeanddate.com/worldclock/fixedtime.html?iso=20200806T2100

Here are the connection details via zoom. **Note, the event will be recorded. So if you do not want to be on, please mute your video or take other appropriate actions.** I'd be happy if someone could volunteer to act as CoC facilitator. Please reach out to me or @tkphd.

```
Topic: A guided tour around hpc-carpentry
Time: Aug 6, 2020 11:00 PM Amsterdam, Berlin, Rome, Stockholm, Vienna

Join Zoom Meeting
https://us02web.zoom.us/j/83368083438

Meeting ID: 833 6808 3438
One tap mobile
+496950502596,,83368083438# Germany
+496971049922,,83368083438# Germany

Dial by your location
        +49 695 050 2596 Germany
        +49 69 7104 9922 Germany
        +49 30 5679 5800 Germany
        +49 69 3807 9883 Germany
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Germantown)
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        +1 646 558 8656 US (New York)
        +1 669 900 9128 US (San Jose)
Meeting ID: 833 6808 3438
Find your local number: https://us02web.zoom.us/u/kRYXeBeXW
```

The developing pad can be reached here
https://pad.carpentries.org/hpccarpentry-tour

Looking forward to meeting you tomorrow.

**Comment by hudaibeid** [comment]
I'd be interested as well.

**Comment by tkphd** [comment]
The recording of our Aug. 6 tour is up! https://youtu.be/BFTPW8c9eqc

**Comment by ajdabrowski** [comment]
Also interested in joining!

**Comment by psteinb** [comment]
Feel free to join!
The agenda and notes are here https://codimd.carpentries.org/ct7yfc_LSseoC8mEmbVEiQ?both#

**Comment by tkoskela** [comment]
Also happy to join!

**Comment by reid-a** [comment]
Just in case anyone is watching this and not the other one, there's an issue in this repo (issue #20 ) about scheduling the second task force meeting, currently planned for Oct. 13.

**Comment by tkphd** [comment]
Closing this early planning "document" as more recent efforts, implementing the steps @psteinb suggested, are underway.
