### ISSUE TITLE
2023 Elections

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/coordination#124]
Dear @hpc-carpentry/hpc-intro-maintainers,

On behalf of the HPC Carpentry Steering Committee, you are cordially invited to participate in our annual Election!
The [process](https://github.com/hpc-carpentry/coordination/issues/36) is similar to [last year](https://github.com/hpc-carpentry/coordination/issues/114), but we will use Election Buddy to securely manage the voting. 

- If you wish to nominate yourself or someone else for a seat on the Committee, please leave their name and GitHub handle in a comment on this Issue.
  
  ***Ask before nominating someone else.***
- If someone else nominated you,
  - leave a `:+1:` (:+1:) reaction on the nomination to accept.
  - leave a `:-1:` (:-1:) reaction on the nomination to decline.
- Accepted nominations will be added to the official Election Buddy ballot.
- An Election Buddy link will be sent out after two weeks, preceding the June 2023 Coordination Meeting.
- The Election will remain open for one week (the maximum allowed by the platform).
- Please vote for whomever you wish to serve on the Steering Committee (or Lesson Program Governance Committee, should we join The Carpentries this year).
- Any valid nominee receiving _5 or more votes_ at the close of the election shall be considered duly elected.

Sincerely,  
  Andrew Reid, @reid-a  
  Alan O'Cais, @ocaisa  
  Annajiat Alim Rasel, @annajiat  
  Trevor Keller, @tkphd  
  Wirawan Purwanto, @wirawan0
  Rohit Goswami, @HaoZeke 

---

The Steering Committee must have at least three members; no upper limit has been set. Each member will be elected for a term of one (1) year. The members are expected to foster the HPC Carpentry organization and its lessons, guide curriculum development following The Carpentries Handbook, and participate in discussions with The Carpentries in a representative capacity to help us navigate the pathway to induction as an official Lesson Program. An important additional task of this inaugural Steering Committee will be to formalize a set of by-laws outlining our governance structure. The time commitment of service on the Steering Committee is unknown, but is not negligible.

Participation in some of the recent Coordination Meetings and Coworking Hours this year is desirable, but not a strict prerequisite: these elections are democratic, and any member of our community is eligible to join the Steering Committee. In case of scheduling conflicts with the existing meeting times, the monthly Coordination meeting time will be changed so that issues of governance may be discussed with full participation of all members of the Committee.

**Comment by tkphd** [comment]
Nomination: ___Andrew Reid___, @reid-a

**Comment by tkphd** [comment]
Nomination: ___Alan O'Cais___, @ocaisa

**Comment by tkphd** [comment]
Nomination: ___Annajiat Alim Rasel___, @annajiat

**Comment by tkphd** [comment]
Nomination: ___Trevor Keller___, @tkphd

**Comment by tkphd** [comment]
Nomination: ___Wirawan Purwanto___, @wirawan0

**Comment by annajiat** [comment]
Thank you @tkphd

**Comment by tkphd** [comment]
Dear HPC Carpentry community,
Elections for the HPC Carpentry Steering Committee goes live at midnight UTC!
Please visit the following link to cast your ballot before [11:45 PM UTC on June 22](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20230622T2345&p1=0&msg=HPC+Carpentry+Ballot+Closes):

https://secure.electionbuddy.com/m/HPCCarp/sc2023

Sincerely,
Trevor Keller *on behalf of the current Steering Committee*
