### ISSUE TITLE
default branch is main

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/coordination#15]
FYI, the default branch on this repository is now ***main***. Please update clones & forks accordingly.

### Local clones

```bash
$ git br -m master main
```

### Personal forks

```bash
$ git push fork_address_or_alias main
```

Then, login to GitHub, visit the fork, go to Settings tab, then the Branches field. Set the default to ***main***.

Finally, go back to the Code tab, select the Branches field, and delete "master".

**Comment by psteinb** [comment]
I am happy to change. Thanks for taking the action.
