### ISSUE TITLE
Coordination meeting in September

### ISSUE THREAD

**Issue by ocaisa** [hpc-carpentry/coordination#17]
We said during the CarpentryCon2020 session that we would organise a meeting in September. To do that we need to sort out a few issues:

- [ ] Time and date
  * There is already [a wiki item for this in hpc-intro](https://github.com/hpc-carpentry/hpc-intro/wiki/Task-Force-Meeting-2020-09) (for Sept. 16th) but I wonder if this should not be a little more general and in the coordination repo? Or are we planning to have one meeting per repo?
  * The date there has been set to Sept. 16 but timing is going to be tricky since we have interest from very diverse time zones, I expect that we will have to follow the example of the [HPC intro walkthrough](https://github.com/orgs/hpc-carpentry/teams/hpc-intro-maintainers/discussions/4)
- [ ] Tool
  * Zoom seems like the reliable option, at least until we can agree on an alternative
- [ ] Agenda

I think the agenda is something we can hopefully converge on in this issue. I'm putting a proposal here that we can update as people comment on this issue and we can then update the wiki page once we converge a bit:
* Task Force modus operandi (initial suggestions in brackets)
  * Initial discussion in https://github.com/hpc-carpentry/coordination/issues/12
  * Lifetime (3 months, renewable)
  * Minimum/maximum sizes (1/4)
  * Where to define main task (Milestone in repo)
    * Subtasks (issues and PRs)
  * Time commitment (co-working time of 1 hour a week)
* Updates on lesson development
* New lesson plans/proposals
* Task definitions and volunteers
  * Potential tasks
    * Diversity
    * Carpentries incubator
    * Making hpc-intro ready for a beta release, https://github.com/hpc-carpentry/hpc-intro/issues/174
    * GitHub triage
    * Updating the landing page
    * ...
* Regular coordination meetings
  * Which meeting tool?

**Comment by HaoZeke** [comment]
I think we might need to flesh out the content in hpc-intro a bit more, and can merge it into the shell lesson (with that being prepended). Looking at close examples like the [R-novice-inflammation lesson](https://github.com/swcarpentry/r-novice-inflammation/), or the equivalents in DC, we need more content.

**Comment by aturner-epcc** [comment]
@HaoZeke The hpc-shell lesson was already deliberately split out from the hpc-intro material based on previous discussions and experiences of running the material. The reasoning behind this is that some learner groups may be experienced in use of command line but not using remote HPC resources (in which case, you just need the hpic-intro lesson) while some learner groups may need both hpc-shell and hpc-intro. It is simple to tie the two lessons together into one workshop (see, for example: https://archer-cse.github.io/2019-12-09-epcc-hpcshell/) and having them separate gives you the flexibility to run the hpc-intro part without hpc-shell (and possibly with some additional material afterwards if you want).

Happy to discuss the pros and cons of this again but there was quite a lot of previous discussion on this before the decision was made.

**Comment by aturner-epcc** [comment]
@ocaisa I think you are right that we will need two sessions to cover the diverse time zones. Is there any scope for splitting the agenda between the two sessions (ideally to match on to what different people in different zones are working on)? Or, alternatively, having the coordination meetings once a month and alternating the split agenda each month? If this does not appeal, we will just need to run the same agenda twice.

**Comment by aturner-epcc** [comment]
Can we add "New lesson plans/proposals" to the agenda?

**Comment by ocaisa** [comment]
@aturner-epcc I added an item for that

> Can we add "New lesson plans/proposals" to the agenda?

Done

**Comment by psteinb** [comment]
I secured a zoom call for Sep 16:

Topic: HPC Carpentry Task Force Kick-Off
Time: Sep 16, 2020 08:00 PM Amsterdam, Berlin, Rome, Stockholm, Vienna

Join Zoom Meeting
https://us02web.zoom.us/j/84058724130

Meeting ID: 840 5872 4130
One tap mobile
+496950502596,,84058724130# Germany
+496971049922,,84058724130# Germany

Dial by your location
        +49 695 050 2596 Germany
        +49 69 7104 9922 Germany
        +49 30 5679 5800 Germany
        +49 69 3807 9883 Germany
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Germantown)
        +1 312 626 6799 US (Chicago)
        +1 346 248 7799 US (Houston)
        +1 646 558 8656 US (New York)
        +1 669 900 9128 US (San Jose)
Meeting ID: 840 5872 4130
Find your local number: https://us02web.zoom.us/u/kdSsx7bMoh
