### ISSUE TITLE
Possible hpc-parallel lesson

### ISSUE THREAD

**Issue by aturner-epcc** [hpc-carpentry/coordination#2]
As a next step after 'hpc-intro' I would like to have a hpc-parallel lesson.

One draft learner profile:

"Kaneda has been along to hpc-shell and hpc-intro and has got up and running with his materials science research on an HPC system. He can submit jobs for the initial set of input decks he is running but now needs to move to larger simulations and run more of them across various input parameters. He has been advised that his current job submission script is probably not an efficient setup for the larger simulations and he is concerned that he will not be able to manage to submit the large number of jobs he requires manually."

I am thinking of a day long workshop covering the following topics:

* Summary of shared-memory and distributed memory parallelism and implications for using HPC systems
* What are MPI and OpenMP?
* Parallel job launchers (mpiexec, mpirun, aprun, ...) and links to batch job scripts
* Minimal benchmarking approaches
* Task farming using job arrays and gnu parallel

What do people think? Anyone else interested in helping out?

**Comment by ChristinaLK** [comment]
I like the separation of the parallel items from the `hpc-intro` materials. 
One thing to check is overlap between current python / chapel lessons.

**Comment by ChristinaLK** [comment]
https://github.com/hpc-carpentry/hpc-intro/issues/21

**Comment by psteinb** [comment]
I took a stab at this with [this lesson](https://psteinb.github.io/hpc-in-a-day/02-01-estimate-of-pi/) and the following. I'd be happy to contribute this material, if people agree @aturner-epcc @ocaisa @tkphd.

**Comment by tkphd** [comment]
@psteinb's [pi computation](https://psteinb.github.io/hpc-in-a-day/02-01-estimate-of-pi/) is classic and cool, albeit pleasantly parallel.
@davidhenty's [sharpening an image](https://github.com/davidhenty/sharpen) requires communication, and can be used to discuss Amdahl's law.

**Comment by psteinb** [comment]
To be fair, I use [pi computation](https://psteinb.github.io/hpc-in-a-day/02-01-estimate-of-pi/) to discuss Amdahl's law as well.

I have to admit that the estimate pi is for sure not fit to soothe all learners likings. For example, having taught
[hpc-in-a-day](https://psteinb.github.io/hpc-in-a-day) to mostly life science socialized users I come to the conclusion that a
decent number of learners from this domain struggles to appreciate the idea behind this examples. Most of them do understand
what needs to be parallelized, but not why this Monte Carlo approach works.

So I support the idea of having multiple of such compute bound problems in stock for hpc-carpentry that serve well the teaching
goal of bringing the fundamentals of parallelisation to our learners.

**Comment by davidhenty** [comment]
The disadvantage of my Image Sharpening example is that the code is rather long and, if you want to explain the algorithm, it takes a while. For us, a big advantage is that it does file I/O which means that on our systems it falls over if you run from your home directory - we have a separate /work/ filesystem which users have to use for all I/O from parallel jobs. Viewing the output also serves as a way of checking that people's X-Windows forwarding is all set up OK, although that's much less of an issue now we recommend MobaXterm over putty/Xming.

**Comment by tkphd** [comment]
I would be content to provide a link to an explanation of the algorithm for the interested learner, mention that the details are beyond the scope of the workshop, and move on. The effect of the algorithm makes clear what it's doing, even if the specifics of "how" are a bit fuzzy.

**Comment by psteinb** [comment]
Mmmh, frankly speaking I'd consider @tkphd's approach a double sided medal. For a majority of users that I taught Amdahl's law
and simple parallelisation with `multiprocessing`, they draw many benefits from the fact that they understand the algorithm. And
even here, the estimate pi approach is confusing for some.

**Comment by tkphd** [comment]
Ah, yeah, point conceded -- understanding the algorithm is pretty important to understanding why the scaling goes as it does. 

It's good to have options for which parallel examples we have prepared to teach. I suppose that the drawback of a "more concrete" example is that we need to take more time to explain it.

**Comment by tkphd** [comment]
Peter contributed the [hpc-parallel-novice](https://github.com/hpc-carpentry/hpc-parallel-novice) lesson; I believe this issue is resolved.
