### ISSUE TITLE
2nd HPC Task Force Meeting -- Schedule Info and Open Thread

### ISSUE THREAD

**Issue by reid-a** [hpc-carpentry/coordination#20]
Greetings, HPC Enthusiasts!

In addition to the work underway to set up the co-working hours, we also need to schedule a second task force meeting.

Owing to the geographic distribution of our community, we have decided to have two meetings, one at 0700 UTC, and a second one later the same day at 2100 UTC. The first is meant to be convenient for participants in Europe and Asia, and the second for the Americas, although of course anyone may attend any meeting.

What is not yet settled is the date, and for this we have set up a [poll](http://whenisgood.net/8dgykqi), with candidate dates are Oct. 6, Oct.7, Oct. 13, and Oct. 14.           

Interested participants are invited to complete the poll before Sept. 27, at which point the results will be collected and the date will be announced.

A [draft agenda](https://codimd.carpentries.org/tsMOzEaMQYmeesMGpalVRw?both) is also up at the CodiMD, suggestions for new items are welcome.

**Comment by reid-a** [comment]
The second task for meeting now has a date, it will be on Oct. 13, 2020 -- thanks to all who answered the poll.

I'm also highly conscious of the fact that the chosen time slots and date make it hard for some people to 
contribute. By way of mitigation, everyone is invited to make comments or proposals in this issue thread
throughout the day on the Oct. 13.

Video links will be provided once they are available.

We don't anticipate making any major strategic decisions on the 13th, but hopefully we can get a sense
of our progress and lay some good groundwork.

As of Sept. 29, the draft agenda is:

### Draft Agenda

* Updates on lesson development
    * Is co-working happening, is it effective?
    * What state are the lessons in?
    * Has anyone road-tested any of the content?
    * Do we want a pedagogical review? Who could do this?
* Interaction with Carpentries
    * How do we decide if we're ready for the incubator?
    * Do we need resources from them? A "stunt cluster"?
    * Style/format issues?
        * Nonsequential lesson numbering [has impacts](https://codimd.carpentries.org/tsMOzEaMQYmeesMGpalVRw?both)
        * The ["main site"](https://github.com/hpc-carpentry/hpc-carpentry.github.io) has an [issue](https://github.com/hpc-carpentry/hpc-carpentry.github.io/issues/22) also.
* Governance
    * Model for distributed, asyncrhonous strategic decision-making?
    * External advisory council?
    * Schedule and times for meetings?
* New business

**Comment by reid-a** [comment]
This issue is still open for agenda items, either here or on the [CodiMD](https://codimd.carpentries.org/tsMOzEaMQYmeesMGpalVRw).

**Comment by colinsauze** [comment]
A time slot between 700 and 2100 UTC would be much better suited to people in Western Europe. For me in the UK those times are currently 8am and 10pm (we'll be on UTC again in a couple of weeks time). At 8am i'd usually be about to leave the house to take my son to school and by 10pm i'll be pretty worn out. Something like 1200 or 1300UTC would be much better.

**Comment by reid-a** [comment]
Yes, there has been significant push-back on the time slots, and I'm definitely open to moving one of the slots, or adding a third slot. The difficulty now is finding a volunteer to host a third meeting. Consider this a solicitation!

**Comment by tkphd** [comment]
Notes from the Second Task Force Meetings are available:
https://codimd.carpentries.org/s/xqQaOnWO-

Attendance was low, with three participants in both sessions. Revising our time slots is a priority.

**Comment by psteinb** [comment]
thanks to all for making these 2 coordination meetings happen!
