### ISSUE TITLE
Task Force Coordination Meeting Time Slot Europe+X

### ISSUE THREAD

**Issue by psteinb** [hpc-carpentry/coordination#21]
Many have reported that the current times for the Task Force Coordination Meeting does not match their timezone(s) working hours too well. As we want to keep the frequency of meetings low and yet allow people to participate, this issue is meant to converge on a new time slot.

That said, the meeting is currently hosted by @ocaisa and myself and hence we take the liberty of suggesting two time slots. The meeting will occur once a month. The next meeting will take place in the week of Nov 9 - 13, 2020.

Below, you will find 2 comments that indicate an option. Please vote on them with :+1: or :-1: to indicate your preference. If you feel, that neither of the options presented serve you, leave a comment.

**Comment by psteinb** [comment]
Option 1: Nov 13, 2020, at 10am CET or 8 am UTC.

**Comment by psteinb** [comment]
**Option 2**: Nov 13, 2020, at 2pm CET or 12 pm UTC.

**Comment by hot007** [comment]
Best option for East coast Australia here is 7pm so that's a bit iffy. I think I can manage that one but just noting. I acknowledge Au/NZ represent a horrible range of timezones though!

**Comment by tkphd** [comment]
Note that the Americas-centric meeting will probably remain at 9PM UTC, which is 8AM for Eastern Australia, if the earlier fringe of the day suits you better, @hot007.

**Comment by bkmgit** [comment]
It may be of interest to swap the times for Europe  7 UTC and Asia 13 UTC though maybe having an agenda which meetings may be most useful to join.

**Comment by dpshelio** [comment]
> **Option 1**: Nov 13, 2020, at 10am CET or 8 am UTC.

@psteinb I think that by that date [UTC and CET are only 1 hour apart](https://www.timeanddate.com/worldclock/fixedtime.html?msg=HPC+event&iso=20201113T10&p1=195). Same correction is needed for Option 2.

**Comment by psteinb** [comment]
Thanks for the correction, @dpshelio

**Comment by psteinb** [comment]
This mini survey concludes that we meet weekly at 10am on Thursday.

**Comment by tkphd** [comment]
The Coworking Hours are held Biweekly, or fortnight-ly, not weekly. Every other Thursday.

**Comment by tkphd** [comment]
My understanding is that the Europe+X vidcon has merged with the 1200 UTC Asia+Pacific meeting. If so, @psteinb & @ocaisa, please confirm & close.

**Comment by psteinb** [comment]
@tkphd this is the case yes.
