### ISSUE TITLE
November 2020 HPC Carpentry Task Force meeting

### ISSUE THREAD

**Issue by reid-a** [hpc-carpentry/coordination#23]
The November HPC Carpentry task force meeting will take place the week of Nov. 16-20.

There is a [poll](http://whenisgood.net/stdfe2y) to select a date, and we are soliciting volunteers to host sessions. I will host one at 2200 UTC (5pm US Eastern Standard Time). The date poll will close Wednesday, Nov. 11.

The draft agenda is up on the [CodiMD](https://codimd.carpentries.org/_GcvhRerT4aGX7vnTxI4iA?view), I'm trying to centralize the agenda itself there, but suggestions are welcome via any channel.

**Comment by reid-a** [comment]
Hello agian all!

I neglected to update this after we selected a date, it's *tomorrow*, Nov. 17.

There will be two sessions, one at 1200 UTC hosted by Annajiat and Benson (thank you!), and one at 2200, hosted by me.

Connection info is (or soon will be) on the [CodiMD](https://codimd.carpentries.org/_GcvhRerT4aGX7vnTxI4iA?both) page.

**Comment by tkphd** [comment]
Local times:
* [1200 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20201117T1200&msg=HPC+Carpentries+Coordination) hosted by Benson Muite and Annajiat Alim Rasel
* [2200 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20201117T2200&msg=HPC+Carpentries+Coordination) hosted by Andrew Reid

**Comment by reid-a** [comment]
Meeting took place.  See the comments on the [codimd](https://codimd.carpentries.org/_GcvhRerT4aGX7vnTxI4iA) page.
