### ISSUE TITLE
team member visibility

### ISSUE THREAD

**Issue by psteinb** [hpc-carpentry/coordination#25]
@aturner-epcc @symulation @ChristinaLK @joeybernard @jstaf @razoumov I was just asked by a hpc-intro contributor who is a member of the hpc-carpentry team. 
https://github.com/orgs/hpc-carpentry/people
on the above page, all team members except myself and jstaf have private visibility enabled. Can you please change this to "public"? This way, people that want to contribute, know whom to ask.

**Comment by tkphd** [comment]
Individual members of the team are in control of their public visibility. As is just, admins have no power over these settings. This issue is not actionable.
