### ISSUE TITLE
January 2021 HPC Coordination Meeting

### ISSUE THREAD

**Issue by reid-a** [hpc-carpentry/coordination#27]
Hi all --

  Apologies for the slightly late notice, but hopefully enough
people have been following on the slack channel.

  We will have an HPC Carpentry task force coordination meeting
Jan. 21, 2020, with sessions at 1200 UTC and 2200 UTC.  The
agenda and connectivity info is on the CodiMD here:
https://codimd.carpentries.org/j7wbzKFhRpKB8xgJKbyorg?both

  Feel free to host additional sessions!

**Comment by tkphd** [comment]
## Summary of Action Items

Synthesized from the [meeting notes](https://codimd.carpentries.org/j7wbzKFhRpKB8xgJKbyorg?view).

- [ ] @ocaisa & @annajiat: reach out to Mumtahinah Sristy for a more complete graphics suite based on their [winning design](https://github.com/hpc-carpentry/hpc-carpentry.github.io/issues/28#issuecomment-729230704).
- [ ] @tkphd: Schedule a Sprint (or two) to clear Issues and PRs using Toby's excellent outline for an asynchronous iterative process.
- [ ] @tkphd: Revise Martha's Rules proposal to clarify intent (just the GitHub Issue for discussion & thumbs-up, thumbs-down mechanism for weighing in)
- [ ] @psteinb: "Indeed, one of my TODOs this year will be to investigate with Kari and others from the carpentries team, how our community can move closer to the carpentries. For this, the roadmap @tobyhodges shared is the recipe to go along with." ([Slack, Jan. 12, 2021](https://swcarpentry.slack.com/archives/CEXAZR52T/p1610546969088300?thread_ts=1610477011.086500&cid=CEXAZR52T)).
- [ ] @psteinb: Transfer ownership of <https://github.com/psteinb/hpc-parallel-novice> at will. Suggest / nominate / contact potential maintainers for ongoing support.
- [ ] @tkphd & @reid-a: Draft a proposal for staging democratic elections for a steering committee.

**Comment by psteinb** [comment]
I'd love to start the process of transferring ownership of `psteinb/hpc-parallel-novice` but I wonder how? @tkphd any hints?

**Comment by tkphd** [comment]
@psteinb in the repository's Settings, scroll down to the Danger Zone. There should be an option to Transfer Ownership. Select hpc-carpentry, and it'll be ours!

**Comment by psteinb** [comment]
"This may take a few minutes." Never thought this feels to gratifying.
