### ISSUE TITLE
Adopt Martha's Rules for asynchronous consensus building

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/coordination#28]
[Martha's Rules](https://third-bit.com/files/2020/08/marthas/) have come up a few times in discussions of the HPC Carpentry's governance model which, to date, has been informal and ill-defined. While the name plays on Robert's Rules of Order, a notorious system for parliamentary process, the distillation recommended by Greg Wilson in the above link basically uses issues on GitHub to capture the discussion, evolution, and adoption of new ideas using a consensus-building framework.

A similar approach was used to adopt our [new logo](https://github.com/hpc-carpentry/hpc-carpentry.github.io/issues/28). 

When an issue of relevance to the HPC Carpentries comes up, I propose that we employ the mechanism of Martha's Rules to identify solutions, capture discussion and linked alternatives, build consensus on the most agreeable approach, and vote (using emoji) to adopt or reject the proposal and any proposed alternatives. Adopting such a process will help to remove uncertainty from this effort: there will be a clear record of the concept and required tasks, some notion of ownership of the solution, and, once consensus is reached, a clear signal to proceed, which may be lacking at present.

Please comment on this issue, or vote in favor (with any clearly positive emoji, such as :+1: ) or in opposition (any negative emoji, e.g. :-1:), that we adopt the following process.

---

1. Anyone may sponsor a proposal by filing an issue in the [Coordination](https://github.com/hpc-carpentry/coordination) repository tagged “proposal”. 
    - The sponsor of a proposal is not necessarily responsible for implementing it, though they can volunteer for that role.
    - As a worldwide team, a lot of discussion will be asynchronous. Clear and complete presentation of the Proposal in the sponsoring Issue is encouraged.
1. Proposals must include:
    - a one-line summary (the subject line of the issue)
    - any required background information, including linked issues
    - the full text of the proposal
    - pros and cons
    - possible alternatives
1. Members of the community are invited to indicate their sense of the proposal:
    - Who likes the proposal? React with :+1: (`:+1:`)
    - Who can live with the proposal? React with :eyes:  (`:eyes:`)
    - Who is uncomfortable with the proposal? React with :-1:  (`:-1:`)
1. Discussion of the proposal can occur as comments on the Issue, in the Slack channel, on the TopicBox mailing list, and during the next Coworking Hours. 
1.  At least 24 hours prior to the next Coordination Meeting, add the "coordination" label, and check to make sure the proposal is included in the agenda for discussion. 
    - When the proposal comes up, if the sponsor is present, they will be given time to present the proposal. If they are not, but the proposal was presented in an earlier meeting, time will be taken to read the notes on the presentation.
    - Every meeting attendee will review and update their vote on the proposal.
1. If any members are uncomfortable they can briefly state their objections. A 10 minute timer is then set for a brief discussion moderated by the facilitator.
1. After 10 minutes or when no one has anything further to add, whichever comes first, each attendee shall update their vote based on the discussion.
1. If the proposal has received fewer than 5 votes (a quorum), or there are more Coordination Meetings to come in other time zones, then the topic is tabled for discussion until the next meeting (Coordination *or* Coworking Hour).
1. If this is the last of the Coordination Meetings for the day, and all votes are either in favor :+1: or not opposed :confused:, then the proposal is accepted.
1. If any votes are in opposition :-1:, the proposal is referred back to the sponsor for further work.
    
---

Edits:

* 2021-01-21 by @tkphd 
    - Scope: we don't need the full suite of Martha's Rules, only the asynchronous democratic process. 
    - Revised to reflect the fact that our Group requires more than one meeting.
    - Hammered out an actual Process. It reads as stiffly formal, but leeway will be afforded for all manner of exigencies.

**Comment by tkphd** [comment]
An objection has been [raised](https://codimd.carpentries.org/j7wbzKFhRpKB8xgJKbyorg?view#Governance) regarding Martha's Rules' requirement of a quorum to decide. It is unclear what that term means for HPC Carpentry, which has a flat structure of indeterminate size. 

It was suggested that we define the quorum as 50% of the "governing body," which is plausible, but we have not yet defined such a thing [*de jure*](https://en.wikipedia.org/wiki/De_jure). We have a group of six meeting coordinators, which could be thought of as a [*de facto*](https://en.wikipedia.org/wiki/De_facto) set of leaders, but there has been no community discussion of who these characters are (myself included). Perhaps a referendum on our leadership is in order.

An alternative definition of a quorum would be 50% of the attendance of the most recent pair of Coordination Meetings.

**Comment by tkphd** [comment]
See discussion in 2021-01-21 Coordination Meeting: https://codimd.carpentries.org/j7wbzKFhRpKB8xgJKbyorg?view#Governance

**Comment by ocaisa** [comment]
Maybe we can bootstrap the "governing body" into existence via the current setup? We can propose the current set of coordinators as a governing body as a proposal in an issue, and ask people in the organisation to vote on that issue (Like/Live/Uncomfortable). In the next meeting, we take those votes as the baseline for the item. Step 7 is hard in this setup but I guess we can provide an update in the issue and ask people to vote again if it comes to that.

Anyone uncomfortable should try to come along to the next meeting (or use a proxy) so we can discuss it in person and rework it if necessary.

**Comment by tkphd** [comment]
I agree somewhat, @ocaisa. @reid-a & I discussed this in the second coordination meeting yesterday. It would be better, in my (and I think our) opinion, to make this a more-democratic process, with public nominations and elections ~and intrigue and bitter rivalries~. Per the first meeting's [Governance](https://codimd.carpentries.org/j7wbzKFhRpKB8xgJKbyorg?view#Governance) discussion, the process would be:

1. Take a census of our current membership.
  - [ ] Open a new CodiMD for recording membership.
  - [ ] Go through the [Logo](https://github.com/hpc-carpentry/hpc-carpentry.github.io/issues/28) thread, recording everyone who reacted as the first-order approximation of our community base.
  - [ ] Post requests to self-select on the TopicBox, Slack, and GitHib, to check the box by your name if it's already there, or add a checked entry for yourself if we missed you.
  - [ ] Set a deadline of 14 days for responses.
2. Convert the census into a new team on this organization (e.g., hpc-carpentry-members or hpc-carpenters).
3. Solicit nominations from the full membership, for inclusion in an advisory / steering / executive council of co-leaders (or co-responsible adults).
4. Hold elections for *n* seats on the panel, to serve for a term of one year.

We anticipate some overlap between the existing cluster of folks active in our meetings and the eventual advisory council, but it feels less slimy to allow members of the community to express satisfaction (or otherwise) than to self-appoint.

**Comment by tkphd** [comment]
Updated the Proposal with an actual process. It reads stiffly formal, but of course it is not to be practiced that way. Like speed limits, it's only a suggestion.

**Comment by bkmgit** [comment]
Seems good. May want to compare with other software, data and library carpentry.

**Comment by tkphd** [comment]
Toby Hodges reports that the authors of the [Research Software Engineering with Python](https://merely-useful.github.io/py-rse/) book use Martha's Rules [to make team decisions](https://merely-useful.github.io/py-rse/teams.html#teams-martha). He mentioned that most Carpentries teams only claim a single lesson for their scope, and haven't adopted Martha's or similarly structured decision-making process. Our efforts are more ambitious, and we have a lot of participation, so formal organization is more important.

**Comment by tkphd** [comment]
@hpc-carpentry/hpc-intro-maintainers if you have not already read this Proposal and commented or voted, please do so soon. We're trying to democratize and give everyone a voice. Thanks!

**Comment by tkphd** [comment]
@hpc-carpentry/hpc-intro-maintainers With six :+1:  and no objections, IT IS SO ORDERED.
