### ISSUE TITLE
Include hpc-parallel-novice as an introduction to parallelisation

### ISSUE THREAD

**Issue by psteinb** [hpc-carpentry/coordination#29]
I propose to include [psteinb/hpc-parallel-novice](https://psteinb.github.io/hpc-parallel-novice/) into hpc-carpentry. Here are some thoughts that motivate this:

  - the material was taken from [hpc-in-a-day](https://github.com/psteinb/hpc-in-a-day) and is ready for being taught
  - the lesson itself takes learners through the basic steps from serial to parallel code using python
  - I taught this lesson about 10-12 times by now (2 times in 2020) to different audiences
  - the lesson starts with profiling serial code, calculating an expectation what to gain from parallelisation and the diving in to several parallelisation schemes:
    - shared memory parallelisation with `multiprocessing`
    - distributed parallelisation on a client-server architecture with `dask`
    - high-throughput parallelisation using one-job-one-file approaches and map-reduce
    - bonus: a guided tour through distributed parallelisation with `mpi4py`
    - a gpu lesson is missing for now

I believe, hpc-carpentry currently misses a introduction to parallel computing compatible with the average novice HPC user, so I think this would be a nice addition.

This relates to the discussion of #2 which for me didn't reach a consensus. By providing this ready-made and tested material, I hope to offer the community a way forward. Feedback or contributions are highly welcome.

**Comment by bkmgit** [comment]
This would be helpful. I think it would be nice to provide tracks in several languages in addition to Python. Some other nice examples are available at:
http://hpcuniversity.org/students/weeklyChallenge/resources/
Some of the examples include a Sudoku solver as well as a forest fire simulation.

**Comment by reid-a** [comment]
Pro: Provides a separate discussion about parallelism, and a clearer and more accessible parallel code, since Python is easier to read than C. Also includes the "mpirun' mechanics, and so could supplant the existing "cpi" C example. The fact that it quantifies the performance gain is a major advantage, this is missing from the current cpi example.

Con: Looks like it lengthens the lesson? Maybe review the timing. 

I am in favor!

**Comment by tkphd** [comment]
My impression is that the lesson would be a separate, stand-alone not an addition to an existing lesson. @psteinb ?

**Comment by psteinb** [comment]
Precisely, I think this lesson can stand independently within hpc-carpentry.

**Comment by tkphd** [comment]
Referenced in 2021-01-21 Coordination meeting: https://codimd.carpentries.org/j7wbzKFhRpKB8xgJKbyorg?view#Intro-to-Parallelization

**Comment by psteinb** [comment]
hpc-parallel-novice is now part of hpc-carpentry. Thank you all for trust, I earned.
