### ISSUE TITLE
Steering Committee Elections 

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/coordination#44]
@hpc-carpentry/hpc-intro-maintainers:

Per #36, we are holding elections for the HPC Carpentry Steering Committee. Any nominee receiving *5 or more votes* will be elected.

The Steering Committee must have at least three members; no upper limit has been set. Each member will be elected for a term of one (1) year. The members are expected to foster the HPC Carpentry organization and its lessons, guide curriculum development following The Carpentries Handbook, and participate in discussions with The Carpentries in a representative capacity to help us navigate the pathway to induction as an official Lesson Program. An important additional task of this inaugural Steering Committee will be to formalize a set of by-laws outlining our governance structure. The time commitment of service on the Steering Committee is unknown, but is not negligible.

Participation in some of the recent Coordination Meetings and Coworking Hours to date is desirable, but not a strict prerequisite: these elections are democratic, and any member of our community is eligible to join the Steering Committee. In case of scheduling conflicts with the existing meeting times, a separate recurring Steering Committee meeting will be arranged so that issues of governance may be discussed with full participation of all members of the Committee.

## Nominations

* ***Ask before nominating someone else.*** In the event a nominee wishes to decline a nomination, they should do this in a comment on the election issue. The comment nominating them will then be struck through (not deleted, in case of repeat nominations).
* To nominate a community member, please leave a comment with *a single name and GitHub handle*.
* Vote on as many nominees as you wish by "reacting" to their name with `:+1:` (:+1:, in favor).
* If you do not support any nominee, indicate your participation (or abstention) by reacting to the top-level issue comment with `:eyes:` (:eyes:, seen it). This will help us calculate the "quorum" needed for the next vote.
* A nominee receiving at least a majority of the quorum of votes in favor, and less than a minority of votes opposed, shall be elected to a seat.
* As an asynchronous process, nominations and voting can (and should) be conducted simultaneously.
* The Election Issue shall remain open for at least one week, or until the next Coordination Meeting, whichever duration is longer.

## Basic Bylaws

* The Steering Committee shall have at least three active members.
* Seats on the Steering Committee shall come up for election annually.
* In the event that a seat is vacated, voluntarily or following removal, a by-election may be held.

**Comment by tkphd** [comment]
Andrew Reid, @reid-a

**Comment by tkphd** [comment]
Alan O'Cais, @ocaisa

**Comment by tkphd** [comment]
Trevor Keller, @tkphd

**Comment by HaoZeke** [comment]
Rohit Goswami, @HaoZeke

**Comment by annajiat** [comment]
Annajiat Alim Rasel, @annajiat

**Comment by wirawan0** [comment]
Wirawan Purwanto, @wirawan0

**Comment by tkphd** [comment]
Thank you for participating in the inaugural HPC Carpentry Steering Committee Election! 
Per the tallied votes, our Committee comprises:

* Andrew Reid @reid-a 
* Alan O'Cais @ocaisa 
* Annajiat Alim Rasel @annajiat 
* Trevor Keller @tkphd 
* Wirawan Purwantao @wirawan0
