### ISSUE TITLE
Lessons should be turned into template repositories

### ISSUE THREAD

**Issue by ocaisa** [hpc-carpentry/coordination#48]
Turning lessons repos into templates will make it much easier for people to create their own versions for their events

**Comment by ocaisa** [comment]
There was quite a bit of talk about this recently on the HPC Carpentry Slack and there is a clear and obvious downside:

* When you create a repo from a template, you do not retain the git commit history. This means that you can't use your repo to make a PR to the upstream repo (without some Git gymnastics).

What is working for me right now:

* I made my fork of `hpc-intro` and I turn that into a template repository. I then can keep the fork up to date while also being able to easily create specific instances for particular lessons.

I'd be curious to see what recommendations come out with the new lesson template, maybe they have a clever way to approaching the new possibilities (the template option is relatively new).

**Comment by tkphd** [comment]
It looks like all our lesson repos have reverted the "Template Repository" setting. Thanks to whoever did this!
