### ISSUE TITLE
Laundry list of potential topics

### ISSUE THREAD

**Issue by ocaisa** [hpc-carpentry/coordination#7]
There is an ongoing project that seeks to classify HPC skillsets and promote the idea of certifcation.

Just raising awareness, have only glanced over the material yet myself (and note that it does not provide training content, but what should be covered by training content).

https://www.hpc-certification.org/skills/

**Comment by ocaisa** [comment]
Their GitHub repo is at https://github.com/HPC-certification-forum/curriculum

**Comment by ChristinaLK** [comment]
Thanks @ocaisa !

**Comment by psteinb** [comment]
closing this for now. Please reopen at will.
