### ISSUE TITLE
Shell lesson prerequisite for HPC-intro lesson?

### ISSUE THREAD

**Issue by wirawan0** [hpc-carpentry/coordination#70]
Currently we have "hpc-shell" as our own version of UNIX shell lesson. However, in recent coordination/task force meetings there has been a consideration to replace that with Software Carpentry's [shell-novice](https://swcarpentry.github.io/shell-novice/). Each has its own benefits and disadvantages.

hpc-shell:

- (+) it's our own version of the shell lesson, so we can customize it as we see fit for HPC uses
- (-) it's a lot of effort to maintain the lesson and achieve good quality

shell-novice (SwC):

- (+) has been around for a long time, lots of community members, maintainers, ... we get to use their  high quality lesson from the get go
- (+) basic UNIX shell is so important in HPC workflow so this gives an excellent foundation for every learner
- (-) could be an extra burden for learners who need to use HPC (e.g. one more lesson to learn / session to attend).
- (-) it's not owned by us, so we don't get fully tailored lesson.

I open this issue to incite discussion within the larger community. What are your thoughts? See also our recent meeting notes at codiMD (before archived here too): https://codimd.carpentries.org/UrB52XMsTMe_eOypGPqoJw?view .

**Comment by reid-a** [comment]
In the event we proceed with this, there is still a decision to be made about how a workshop should move forward from Shell-novice. Options are, firstly, we modify HPC-Shell to be a "shim" that covers shell issues we need but which are not in the intro lesson, or secondly, we could discard HPC-Shell entirely and incorporate the required content into HPC-Intro.

**Comment by tkphd** [comment]
*Temperature check:* Please react to this comment with a "thumbs up" :+1:, "thumbs down" :-1:, or "eyes" :eyes: to register your opinion in favor, in opposition, or indifferent to the First Option: ***modify HPC-Shell to be a "shim" that covers shell issues we need but which are not in the intro lesson***. This is not a vote *per se*, but will inform the discussion of the Proposal at our next meeting.

**Comment by tkphd** [comment]
*Temperature check:* Please react to this comment with a "thumbs up" :+1:, "thumbs down" :-1:, or "eyes" :eyes: to register your opinion in favor, in opposition, or indifferent to the Second Option: ***we could discard HPC Shell entirely and incorporate the required content into HPC Intro***. This is not a vote *per se*, but will inform the discussion of the Proposal at our next meeting.

**Comment by tkphd** [comment]
The feedback so far has been strongly in favor of Option 2, but it has not been put up for a vote yet. We will put it on the agenda for this month's Coordination Meeting.

**Comment by wirawan0** [comment]
We can close this issue. We have agreed to include useful bits of HPC-shell into HPC-intro.
