### ISSUE TITLE
November 17: BOF @ SC21

### ISSUE THREAD

**Issue by tkphd** [hpc-carpentry/coordination#85]
In lieu of the monthly coordination meeting, we are hosting a hybrid birds-of-a-feather (BOF) and community outreach session on [HPC Carpentry at SC21][bof]. *You must be registered to attend.* It is scheduled to start at 5:15 PM US Central, or **23:15 UTC**. Click to [check your local time][cal]. Video links and the Slido session for Q&A will be available through the [SC21 Hubb][hub].

If you are not attending SC21, we will be monitoring [#hpc-carpentry][hpc] on the Software Carpentry [Slack channel][swc].

[cal]: https://www.timeanddate.com/worldclock/fixedtime.html?iso=20211117T2315&msg=HPC+Carpentry+BOF+SC21
[bof]: https://sc21.hubb.me/fe/schedule-builder/sessions/879730
[hpc]: https://swcarpentry.slack.com/archives/CEXAZR52T
[hub]: https://sc21.hubb.me
[swc]: https://swc-slack-invite.herokuapp.com/

**Comment by tkphd** [comment]
There is a shared notepad for the BOF here:
https://codimd.carpentries.org/9-Y8OaVIT2qpb_P47TR7Lw?both

**Comment by reid-a** [comment]
A PDF of the analytics from the Slido polls is incorporated into this repository. 
https://github.com/hpc-carpentry/coordination/blob/main/conferences/SC21/analytics-report.pdf
